import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  kumikoGenSidebar: [
    {
      type: 'autogenerated',
      dirName: 'kumiko-gen',
    },
  ],
  viewerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'kumiko-gen-viewer',
    },
  ],
  svgToPngSidebar: [
    {
      type: 'autogenerated',
      dirName: 'svg-to-png',
    },
  ],
  changelogSidebar: [
    {
      type: 'autogenerated',
      dirName: 'changelog',
    },
  ],
  inboxSidebar: [
    {
      type: 'autogenerated',
      dirName: 'inbox',
    },
  ],
};

export default sidebars;
